version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"
    reviewers:
      - "yahgwai"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"