name: Security

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run security checks daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    # Skip for release commits to save resources
    if: |
      github.event_name != 'push' || 
      !startsWith(github.event.head_commit.message, 'chore(release):')
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - run: npm ci
    
    # Run npm audit
    - name: NPM Audit
      run: npm audit --audit-level=moderate
    
    # Initialize CodeQL before build
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
    
    # Build the project (CodeQL will analyze during build)
    - name: Build
      run: npm run build
    
    # Perform CodeQL analysis
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
    
    # Check for security updates
    - name: Check for updates
      run: |
        echo "Checking for available security updates..."
        npm outdated || true